### ISSUE TITLE
Cycle Sort

### ISSUE THREAD

**Issue by mendoza** [ccgcv/Cplusplus-for-Hacktoberfest#8]
I think cycle sort could be in this collection since, it's an unstable sorting algorithm, so it's fun to be able to experiment against better optimized sorts
Please assign me to this issue.

**Comment by ccgcv** [comment]
I just added the merge sort algorithm and didn't see the issue first . ( My bad ) . However, you are free to implement any other sorting or searching algorithm and I'll gladly add it. Cheers !

**Comment by mendoza** [comment]
How about the cycle sort?

**Comment by ccgcv** [comment]
Sure. Go ahead ! It'll be really cool to see all algorithms in the repository after the hacktoberfest is over.
